- hosts: all
  tasks:
  - yum_repository:
      description: "Docker Yum repo"
      name: "Docker_repo"
      baseurl: "https://download.docker.com/linux/centos/8/x86_64/stable/"
      gpgcheck: no
    
  - package:
      name: "containerd"
      state: present
      
  - package:
      name: "docker-ce"
      state: present

  - service:
      name: "docker"
      state: started
      enabled: yes

  - name: install docker with pip
    command: pip3 install docker
 
  - file:
      state: directory
      path: "/webserver" 
      
     
  - copy:
      dest: "/webserver/mywebpage.html"
      content: "this is my web site\n"


  - docker_image:
      name: "httpd:latest"
      source: pull

  - docker_container:
      name: "MyWebserver"
      image: "httpd:latest"
      state: started
      exposed_ports:
      - "80"
      ports:
      - "8080:80"
      volumes:
      - "/webserver:/usr/local/apache2/htdocs"
